// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myoveqdzbfgqlcurqupz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15b3ZlcWR6YmZncWxjdXJxdXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjU3NDEsImV4cCI6MjA2MzU0MTc0MX0.U1YmXJllz7e-OL2e4HfNxgg57-uAHor4nyRkloAjHpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);